#!/usr/bin/env bash
CRITERION="10-publishing"
echo "[$CRITERION]"
echo ""
echo "LiveFoldersFS:"
echo "  1. Add folder.yaml to any GitHub repo"
echo "  2. Done. Users install with: livefolders install github.com/you/repo"
echo "  No registry. No npm publish. No PyPI upload."
echo ""
echo "MCP:"
echo "  Option A: publish to npm/PyPI, users add to claude_desktop_config.json manually"
echo "  Option B: list in community MCP registry (no official registry yet)"
echo "  Option C: share repo URL, users clone and configure themselves"
echo ""
echo "  Winner: LiveFoldersFS — one-command install from any GitHub URL"
