#!/usr/bin/env bash
CRITERION="07-composability"
echo "[$CRITERION]"
echo ""
echo "LiveFoldersFS v0.9.0: pipe: field in folder.yaml"
echo "  - declare pipe: [stage1, stage2, ...] on any write_invoke endpoint"
echo "  - runtime chains handlers: stdout of each stage → stdin of next"
echo "  - single LLM write triggers the entire pipeline; no intermediate reads needed"
echo "  - per-stage input: schema validated before each stage executes"
echo "  - any stage error stops the pipeline and returns [ERROR:CODE] immediately"
echo ""
echo "  Example folder.yaml:"
echo "    files:"
echo "      - name: fetch"
echo "        type: write_invoke"
echo "        handler: ./fetch.sh"
echo "      - name: format"
echo "        type: write_invoke"
echo "        handler: ./format.sh"
echo "      - name: report"
echo "        type: write_invoke"
echo "        pipe: [fetch, format]"
echo ""

# Demonstrate: two-stage pipeline using shell commands
STAGE1_OUT=$(echo "london" | tr '[:lower:]' '[:upper:]')
STAGE2_OUT=$(echo "$STAGE1_OUT" | sed 's/^/City: /')
echo "  Pipeline demo (echo → uppercase → prefix):"
echo "    input:  london"
echo "    stage1: $STAGE1_OUT"
echo "    output: $STAGE2_OUT"
echo ""
echo "MCP: compose via Python function calls — clean within a single server"
echo "  Cross-server tool chaining not natively supported; requires LLM orchestration"
echo ""
echo "  Winner: LiveFoldersFS — native declarative pipeline; single write, zero intermediate reads"
echo "          MCP composition requires LLM round-trips across server boundaries"
