#!/usr/bin/env bash
CRITERION="08-observability"
echo "[$CRITERION]"
echo ""
echo "LiveFoldersFS v0.8.0: two observability layers"
echo "  1. Structured error codes in the response stream:"
echo "     [ERROR:HANDLER]       — handler exited non-zero"
echo "     [ERROR:TIMEOUT]       — handler exceeded timeout"
echo "     [ERROR:SPAWN]         — handler failed to start"
echo "     [ERROR:PROCESS]       — unexpected process I/O error"
echo "     [ERROR:INVALID_INPUT] — input failed schema validation"
echo ""
echo "  2. Per-endpoint <endpoint>.log file written after every invocation:"

# Demonstrate log format
DURATION_MS=342
STDERR_CONTENT=""
EXIT_STATUS="ok"
echo "     cat forecast.log"
echo "     duration_ms: $DURATION_MS"
echo "     exit: $EXIT_STATUS"
echo "     stderr: $STDERR_CONTENT"
echo ""
echo "     cat forecast.log  (with stderr)"
DURATION_MS=88
STDERR_CONTENT="warning: rate limit approaching"
EXIT_STATUS="ok"
echo "     duration_ms: $DURATION_MS"
echo "     exit: $EXIT_STATUS"
echo "     stderr: $STDERR_CONTENT"
echo ""
echo "  LLM or monitoring script can read <endpoint>.log without round-tripping through the tool."
echo ""
echo "MCP: Python exceptions auto-converted to structured error objects (type, message, traceback)"
echo "  Strong for programmatic error handling; no timing or stderr capture by default"
echo ""
echo "AgentFS: purpose-built observability substrate — structured audit logs and execution"
echo "  traces as first-class filesystem artifacts (but not a tool-invocation interface)"
echo ""
echo "  Winner: LiveFoldersFS ✓ — structured error codes + per-invocation timing/stderr logs"
echo "          MCP ✓ — structured exceptions; AgentFS ✓ — audit substrate"
echo "          llm9p ✗ — no observability mechanism"
